import miguelRondelli   from '../assets/images/miguel_rondelli.png'
import luisRamos        from '../assets/images/luis_ramos1.png'
import lisandroAlzugaray from '../assets/images/lisandro_alzugaray2.png'
import cusco from '../assets/images/escudo_cusco.webp'
import nicolasSilva from '../assets/images/nicolas_silva.png'
import universitario from '../assets/images/escudo_universitario.webp'
import alianzaLima from '../assets/images/escudo_alianzalima.webp'
import facundoCallejo from '../assets/images/facundo_callejo.png'
import ezequielPiovi from '../assets/images/ezequiel_piovi.webp'
import estudiantes from '../assets/images/estudiantes.png'
import matiasDiBenedetto from '../assets/images/matias_dibenedetto.png'
import franciscoFydriszewski from '../assets/images/francisco_fydriszewski.png'
import independienteMedellin from '../assets/images/dim.png'
import cainFara from '../assets/images/cain_fara.png'
import juanruizgomez from '../assets/images/juan_ruizgomez.png'
import emelec from '../assets/images/emelec.webp'
import hectorFertoli from '../assets/images/hector_fertoli.png'
import andresZanini from '../assets/images/andres_zanini.png'
import depLaSerena from '../assets/images/deplaserena.png'
import julianAquino from '../assets/images/julian_aquino.png'
import atlanta from '../assets/images/atlanta.png'


export const players = [
  {
    id: 1,
    name: 'Miguel',
    lastname: 'Rondelli',
    club: 'Cusco FC',
    escudo: cusco,
    sizes: { h: '30px', w: '30px' },
    position: 'Director Técnico',
    nationality: 'Argentina',
    image: miguelRondelli,
    bio: 'Director técnico con experiencia en fútbol sudamericano. Metodología de trabajo diferencial y visión moderna del juego.',
    type: 'coach',
    number: 'DT',
    birthDate: '1978-01-24',
    fieldPosition: null,
    stats: {
      matches: 144,
      wins: 70,
      draws: 31,
      losses: 43,
      ratings: { tactica: 85, motivacion: 90, formacion: 88, estrategia: 86 },
    },
    socials: {
      instagram: 'https://www.instagram.com/rondellidt/',
      twitter: 'https://twitter.com/miguelrondelli',
      threads: 'https://threads.com/@miguelrondelli',
    },
  },
   {
    id: 2,
    name: 'Nicolas',
    lastname: 'Silva',
    club: 'Cusco FC',
    escudo: cusco,
    sizes: { h: '30px', w: '30px' },
    position: 'Extremo Derecho',
    number: '26',
    nationality: 'Argentina',
    birthDate: '1990-01-24',
    image: nicolasSilva,
    bio: 'Extremo derecho que milita en la Liga 1 de Perú con Cusco FC. Destacado por su velocidad y capacidad de desborde.',
    type: 'player',
    tags: ['Perú', 'Liga 1'],
    fieldPosition: { x: 80, y: 20 },
    stats: {
      matches: 292,
      goals: 19,
      assists: 26,
      ratings: { pase: 90, vision: 81, regate: 87, disparo: 72, creatividad: 85 },
    },
    socials: {
      instagram: 'https://www.instagram.com/_silvanicolas/',
    },
  },
  {
    id: 3,
    name: 'Luis',
    lastname: 'Ramos',
    club: 'Alianza Lima',
    escudo: alianzaLima,
    sizes: { h: '30px', w: '25px' },
    position: 'Delantero',
    nationality: 'Perú',
    image: luisRamos,
    bio: 'Delantero destacado por su capacidad goleadora y movilidad en el ataque. Pieza clave en el ataque, aportando goles y asistencias importantes.',
    type: 'player',
    number: 9 ,
    birthDate: '1999-12-13',
    fieldPosition: { x: 50, y: 10 },
    stats: {
      matches: 184,
      goals: 55,
      assists: 10,
      cleanSheets: null,
      ratings: { pase: 87, vision: 85, tecnica: 83, disparo: 72, aereo: 88 },
    },
    socials: {
      instagram: 'https://www.instagram.com/luisramos_09/',
    },
  },
  {
    id: 4,
    name: 'Lisandro',
    lastname: 'Alzugaray',
    club: 'Univ de Deportes',
    escudo: universitario,
    sizes: { h: '30px', w: '30px' },
    position: 'Extremo Derecho',
    nationality: 'Argentina',
    image: lisandroAlzugaray,
    bio: 'Extremo derecho con visión de juego y técnica depurada. Con buena capacidad de desborde y creación de oportunidades.',
    type: 'player',
    number: 30,
    birthDate: '1978-01-30',
    fieldPosition: { x: 80, y: 20 },
    stats: {
      matches: 299,
      goals: 69,
      assists: 33,
      ratings: { pase: 90, vision: 85, tecnica: 83, disparo: 77, creatividad: 88 },
    },
    socials: {
      instagram: 'https://www.instagram.com/lisandroalzugaray',
      threads: 'https://www.threads.com/@lisandroalzugaray',
    },
  },
  {
    id: 5,
    name: 'Facundo',
    lastname: 'Callejo',
    club: 'Cusco FC',
    escudo: cusco,
    position: 'Delantero',
    nationality: 'Argentina',
    image: facundoCallejo,
    sizes: { h: '30px', w: '30px' },
    bio: 'Delantero con visión de juego y técnica depurada. Con buena capacidad de desborde y creación de oportunidades.',
    type: 'player',
    number: 9,
    birthDate: '1992-07-02',
    fieldPosition: { x: 50, y: 15 },
    stats: {
      matches: 283,
      goals: 74,
      assists: 15,
      ratings: { pase: 86, efectividad: 89, tecnica: 83, disparo: 93, oportunidades: 88 },
    },
    socials: {
      instagram: 'https://www.instagram.com/facu.callejo19/',
      tiktok: 'https://www.tiktok.com/@facucallejo.19',
      threads: 'https://www.threads.com/@facu.callejo19',
      twitter: 'https://x.com/CALLEJOFACUNDO',
    },
  },
  {
    id: 6,
    name: 'Ezequiel',
    lastname: 'Piovi',
    club: 'Estudiantes LP',
    escudo: estudiantes,
    sizes: { h: '30px', w: '23px' },
    position: 'Volante Central',
    nationality: 'Argentina',
    image: ezequielPiovi,
    bio: 'Volante central con gran capacidad de recuperación y distribución del balón. Fundamental en el equilibrio del equipo.',
    type: 'player',
    number: 5,
    birthDate: '1992-08-20',
    fieldPosition: { x: 50, y: 60 },
    stats: {
      matches: 321,
      goals: 10,
      assists: 16,
      ratings: { pase: 91, vision: 85, recuperacion: 94, distribucion: 88, resistencia: 92 },
    },
    socials: {
      instagram: 'https://www.instagram.com/kekipiovi18/',
    },
  },
  {
    id: 7,
    name: 'Matias',
    lastname: 'Di Benedetto',
    club: 'Univ de Deportes',
    escudo: universitario,
    sizes: { h: '30px', w: '23px' },
    position: 'Defensor Central',
    nationality: 'Argentina / Perú',
    image: matiasDiBenedetto,
    bio: 'Defensor central con gran capacidad de recuperación y organización defensiva. Fundamental en el equilibrio del equipo.',
    type: 'player',
    number: 5,
    birthDate: '1992-11-19',
    fieldPosition: { x: 50, y: 85 },
    stats: {
      matches: 287,
      goals: 11,
      assists: 5,
      ratings: { pase: 86, aereo: 80, recuperacion: 90, distribucion: 88, resistencia: 90 },
    },
    socials: {
      instagram: 'https://www.instagram.com/mati.dibenedetto/',
      threads: 'https://www.threads.com/@mati.dibenedetto',
    },
  },
  {
    id: 8,
    name: 'Francisco',
    lastname: 'Fydriszewski',
    club: 'Ind de Medellín',
    escudo: independienteMedellin,
    sizes: { h: '30px', w: '30px' },
    position: 'Delantero',
    nationality: 'Argentina / Perú',
    image: franciscoFydriszewski,
    bio: 'Delantero aguerrido y con gran capacidad goleadora. Destacado por su potencia física y habilidad para definir en el área.',
    type: 'player',
    number: 19,
    birthDate: '1992-11-19',
    fieldPosition: { x: 50, y: 15 },
    stats: {
      matches: 325,
      goals: 112,
      assists: 29,
      ratings: { pase: 86, aereo: 92, tecnica: 83, disparos: 92, oportunidades: 90 },
    },
    socials: {
      instagram: 'https://www.instagram.com/franciscofydriszewskiok/',
      threads: 'https://www.threads.com/@franciscofydriszewskiok',
    },
  },
  {
    id: 9,
    name: 'Cain',
    lastname: 'Fara',
    club: 'Univ de Deportes',
    escudo: universitario,
    sizes: { h: '30px', w: '30px' },
    position: 'Defensor Central',
    nationality: 'Argentina',
    image: cainFara,
    bio: 'Defensor central con gran capacidad de recuperación y organización defensiva. Eje fundamental en la línea de fondo, solides y liderazgo.',
    type: 'player',
    number: 2,
    birthDate: '1994-03-06',
    fieldPosition: { x: 50, y: 85 },
    stats: {
      matches: 153,
      goals: 4,
      cleanSheets: 35,
      ratings: { pase: 86, aereo: 80, recuperacion: 90, distribucion: 88, resistencia: 90 },
    },
    socials: {
      instagram: 'https://www.instagram.com/caiinfara/',
      threads: 'https://www.threads.com/@caiinfara',
      tiktok: 'https://www.tiktok.com/@cainfara',
    },
  },
  {
    id: 10,
    name: 'Juan',
    lastname: 'Ruiz Gomez',
    club: 'Emelec',
    escudo: emelec,
    sizes: { h: '30px', w: '30px' },
    position: 'Extremo Derecho',
    nationality: 'Argentina',
    image: juanruizgomez,
    bio: 'Delantero con gran visión y capacidad de pase. Jugador clave en la construcción del juego del equipo.',
    type: 'player',
    number: 19,
    birthDate: '1994-01-10',
    fieldPosition: { x: 80, y: 20 },
    stats: {
      matches: 180,
      goals: 22, 
      assists: 13,
      ratings: { pase: 88, vision: 84, recuperacion: 75, distribucion: 87, resistencia: 90 },
    },
    socials: {
      instagram: 'https://www.instagram.com/ruizgomezjp/',
    },
  },
  {
    id: 11,
    name: 'Hector',
    lastname: 'Fertoli',
    club: 'Univ de Deportes',
    escudo: universitario,
    sizes: { h: '30px', w: '30px' },
    position: 'Extremo Izquierdo',
    nationality: 'Argentina',
    image: hectorFertoli,
    bio: 'Extremo izquierdo con gran velocidad y capacidad de desborde. Destacado por su habilidad para generar oportunidades de gol.',
    type: 'player',
    number: 8,
    birthDate: '1994-12-03',
    fieldPosition: { x: 20, y: 20 },
    stats: {
      matches: 359,
      goals: 36,
      assists: 23,
      ratings: { pase: 87, vision: 82, desbordes: 78, distribucion: 84, velocidad: 88 },
    },
    socials: {
      instagram: 'https://www.instagram.com/rayofertoli/',
    },
  },
  {
    id: 12,
    name: 'Andres',
    lastname: 'Zanini',
    club: 'Dep La Serena',
    escudo: depLaSerena,
    sizes: { h: '30px', w: '27px' },  
    position: 'Defensor Central',
    nationality: 'Argentina',
    image: andresZanini,
    bio: 'Defensor central con gran capacidad de recuperación y organización defensiva. Eje fundamental en la línea de fondo, solides y liderazgo.',
    type: 'player',
    number: 2,
    birthDate: '1997-01-18',
    fieldPosition: { x: 50, y: 85 },
    stats: {
      matches: 168,
      goals: 8,
      cleanSheets: 50,
      ratings: { pase: 85, aereo: 87, recuperacion: 91, distribucion: 86, resistencia: 89 },
    },
    socials: {
      instagram: 'https://www.instagram.com/andrees_zani/',
    },
  },  
  {
    id: 13,
    name: 'Julian',
    lastname: 'Aquino',
    club: 'Atlanta',
    escudo: atlanta,
    sizes: { h: '30px', w: '27px' },  
    position: 'Mediocampista Ofensivo',
    nationality: 'Argentina',
    image: julianAquino,
    bio: 'Enganche con gran capacidad de creación y organización ofensiva, ataque, creatividad y visión de juego.',
    type: 'player',
    number: 3,
    birthDate: '1996-04-12',
    fieldPosition: { x: 50, y: 30},
    stats: {
      matches: 19,
      goals: 2,
      assists: 1,
      ratings: { pase: 84, vision: 86, creatividad: 89, distribucion: 85, resistencia: 88 },
    },
    socials: {
      instagram: 'https://www.instagram.com/juli.aquino10/',
    },
  },  

]